# Generated by Django 5.0 on 2023-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_title', models.CharField(max_length=50)),
                ('mov_time', models.DateTimeField()),
                ('mov_year', models.IntegerField()),
                ('mov_lang', models.IntegerField(choices=[(1, 'English'), (2, 'Russian'), (3, 'Tajik')], default=3, max_length=3)),
                ('move_rel_country', models.CharField(max_length=30)),
            ],
        ),
    ]
