# Generated by Django 5.0 on 2023-12-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.IntegerField()),
                ('act_fname', models.CharField(max_length=20)),
                ('act_lname', models.CharField(max_length=20)),
                ('act_gender', models.CharField(max_length=1)),
                ('movie', models.ManyToManyField(related_name='movie_cast', to='movieapp.movie')),
            ],
        ),
    ]
