# Generated by Django 5.0 on 2023-12-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='act_gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, max_length=10),
        ),
    ]
